const assert = require('node:assert/strict');
const {read, toggle, KEY} = require('./app/static/shortlist.js');
let value = null;
const storage = {getItem: key => {assert.equal(key, KEY); return value;}, setItem: (key, next) => {value = next;}};
assert.deepEqual(read(storage), []);
assert.equal(toggle(storage, 'notice-one'), true);
assert.deepEqual(read(storage), ['notice-one']);
assert.equal(toggle(storage, 'notice-one'), false);
assert.deepEqual(read(storage), []);
value = JSON.stringify(['a', 'a', 'b']);
assert.deepEqual(read(storage), ['a', 'b']);
value = 'broken';
assert.throws(() => toggle(storage, 'c'));
assert.equal(value, 'broken');
value = JSON.stringify(Array.from({length:200}, (_, i) => String(i)));
assert.throws(() => toggle(storage, 'extra'), /full/);
assert.equal(toggle(storage, '0'), false);
assert.equal(read(storage).length, 199);
assert.throws(() => read({getItem(){throw Error('blocked');}}), /blocked/);
console.log('Shortlist persistence tests passed; no browser data or network used.');
