"""
notice_sources.py
-----------------
Master registry of every NJ transportation public notice source.
Each source defines:
  - how to crawl it (parser type, URL, selectors)
  - what tier it is (determines crawl frequency and confidence)
  - what source_tier to stamp on extracted records

Tier 1  = State agencies       — fully automated, crawl daily, high signal
Tier 2  = County portals       — automated, crawl daily, medium signal
Tier 3  = Municipal websites   — seeded from SoS directory, weekly, filtered
Tier 4  = Paywalled platforms  — notice text only, weekly
"""

NOTICE_SOURCES = [

    # ─────────────────────────────────────────────────────────────────────────
    # TIER 1 — STATE AGENCIES
    # ─────────────────────────────────────────────────────────────────────────

    {
        "id":           "state-njdot-construction",
        "name":         "NJDOT Construction Services",
        "entity_type":  "State Agency",
        "source_tier":  "state",
        "crawl_tier":   1,
        "county":       "Statewide",
        "url":          "https://www.nj.gov/transportation/business/procurement/ConstrServ/curradvproj.shtm",
        "planned_url":  "https://dot.nj.gov/transportation/business/procurement/ConstrServ/PlannedAdv/",
        "parser":       "njdot_construction",
        "access_type":  "Public access",
        "platform":     "NJDOT website",
        "notice_type":  "construction",
        "crawl_freq":   "daily",
        "notes":        "HTML table. Contract no, description, counties, bid date, download links. Also crawl planned ads page.",
    },
    {
        "id":           "state-njdot-profserv",
        "name":         "NJDOT Professional Services",
        "entity_type":  "State Agency",
        "source_tier":  "state",
        "crawl_tier":   1,
        "county":       "Statewide",
        "url":          "https://www.nj.gov/transportation/business/procurement/ProfServ/CurrentSolic.shtm",
        "parser":       "njdot_profserv",
        "access_type":  "Public access",
        "platform":     "NJDOT website",
        "notice_type":  "professional_services",
        "crawl_freq":   "daily",
        "notes":        "HTML table. TP number, due date, discipline codes (B-1 H-1 etc), project description, status.",
    },
    {
        "id":           "state-njdot-notices",
        "name":         "NJDOT Procurement Notices",
        "entity_type":  "State Agency",
        "source_tier":  "state",
        "crawl_tier":   1,
        "county":       "Statewide",
        "url":          "https://dot.nj.gov/transportation/contribute/business/procurement/notices.shtm",
        "parser":       "generic_html_list",
        "access_type":  "Public access",
        "platform":     "NJDOT website",
        "notice_type":  "public_notice",
        "crawl_freq":   "daily",
        "notes":        "Notices to contractors, EEO, policy updates.",
    },
    {
        "id":           "state-njta",
        "name":         "NJ Turnpike Authority",
        "entity_type":  "State Authority",
        "source_tier":  "state",
        "crawl_tier":   1,
        "county":       "Statewide",
        "url":          "https://www.njta.gov/business-hub/current-solicitations/",
        "parser":       "njta",
        "access_type":  "Public access",
        "platform":     "NJTA procurement portal",
        "notice_type":  "mixed",
        "crawl_freq":   "daily",
        "notes":        "Mixes construction (T-series, P-series) and engineering prof services. Parse both. Docs on BidX.",
    },
    {
        "id":           "state-njtransit",
        "name":         "NJ TRANSIT Procurement",
        "entity_type":  "State Authority",
        "source_tier":  "state",
        "crawl_tier":   1,
        "county":       "Statewide",
        "url":          "https://www.njtransit.com/procurement/calendar",
        "parser":       "njtransit",
        "access_type":  "Free registration required",
        "platform":     "Bid Express",
        "notice_type":  "mixed",
        "crawl_freq":   "daily",
        "notes":        "Free account on BidExpress to view. Calendar page parseable without auth.",
    },
    {
        "id":           "state-drjtbc-construction",
        "name":         "DRJTBC Notice to Contractors",
        "entity_type":  "Bi-State Authority",
        "source_tier":  "state",
        "crawl_tier":   1,
        "county":       "Warren/Hunterdon/Mercer",
        "url":          "https://www.drjtbc.org/construction-services/notice-to-contractors/",
        "parser":       "drjtbc",
        "access_type":  "Public access",
        "platform":     "DRJTBC procurement portal",
        "notice_type":  "construction",
        "crawl_freq":   "daily",
        "notes":        "Construction notices. Bids via Bid Express since Jan 2020.",
    },
    {
        "id":           "state-drjtbc-profserv",
        "name":         "DRJTBC Current Procurements",
        "entity_type":  "Bi-State Authority",
        "source_tier":  "state",
        "crawl_tier":   1,
        "county":       "Warren/Hunterdon/Mercer",
        "url":          "https://www.drjtbc.org/professional-services/current/",
        "parser":       "drjtbc",
        "access_type":  "Public access",
        "platform":     "DRJTBC procurement portal",
        "notice_type":  "professional_services",
        "crawl_freq":   "daily",
        "notes":        "RFPs for engineering, inspection, design. Documents downloadable directly.",
    },
    {
        "id":           "state-dos-legal",
        "name":         "NJ Department of State Legal Notices",
        "entity_type":  "State Agency",
        "source_tier":  "state",
        "crawl_tier":   1,
        "county":       "Statewide",
        "url":          "https://www.nj.gov/state/dos-legal-notices.shtml",
        "parser":       "nj_dos_legal",
        "access_type":  "Public access",
        "platform":     "NJDOS legal notices portal",
        "notice_type":  "public_notice",
        "crawl_freq":   "daily",
        "notes":        "Since Mar 2026 this is the primary statewide legal notice repo. Filter for transportation keywords.",
    },
    {
        "id":           "state-sos-directory",
        "name":         "NJ Secretary of State — Statewide Notice Directory",
        "entity_type":  "State Agency",
        "source_tier":  "state",
        "crawl_tier":   1,
        "county":       "Statewide",
        "url":          "https://www.nj.gov/state/statewide-legal-notices-list.shtml",
        "parser":       "sos_directory",
        "access_type":  "Public access",
        "platform":     "NJDOS legal notices portal",
        "notice_type":  "directory",
        "crawl_freq":   "weekly",
        "notes":        "Seed source — extracts all municipal/county legal notice page URLs. Feed into Tier 3 crawler.",
    },
    {
        "id":           "state-sjta",
        "name":         "South Jersey Transportation Authority",
        "entity_type":  "State Authority",
        "source_tier":  "state",
        "crawl_tier":   1,
        "county":       "Atlantic",
        "url":          "https://www.sjta.com/doing-business/",
        "parser":       "generic_html_list",
        "access_type":  "Public access",
        "platform":     "Agency website",
        "notice_type":  "mixed",
        "crawl_freq":   "daily",
        "notes":        "Atlantic City Expressway construction and maintenance.",
    },
    {
        "id":           "state-treasury",
        "name":         "NJ Treasury Legal Notices",
        "entity_type":  "State Agency",
        "source_tier":  "state",
        "crawl_tier":   1,
        "county":       "Statewide",
        "url":          "https://www.nj.gov/treasury/purchase/bid_op_sites.shtml",
        "parser":       "generic_html_list",
        "access_type":  "Public access",
        "platform":     "NJSTART",
        "notice_type":  "public_notice",
        "crawl_freq":   "weekly",
        "notes":        "Transportation-relevant Treasury procurements. Filter aggressively.",
    },

    # ─────────────────────────────────────────────────────────────────────────
    # TIER 2 — COUNTY PORTALS (21 counties)
    # ─────────────────────────────────────────────────────────────────────────

    {
        "id":           "county-essex",
        "name":         "Essex County Procurement",
        "entity_type":  "County",
        "source_tier":  "county",
        "crawl_tier":   2,
        "county":       "Essex",
        "url":          "https://essexcountynjprocure.org/procure/",
        "legal_url":    "https://essexcountynj.org/current-legal-notices/",
        "parser":       "essex_county",
        "access_type":  "Free registration required",
        "platform":     "County procurement portal",
        "notice_type":  "mixed",
        "crawl_freq":   "daily",
        "notes":        "Dedicated procurement portal. Legal notices on separate page. Registration free for full access.",
    },
    {
        "id":           "county-camden",
        "name":         "Camden County Procurements",
        "entity_type":  "County",
        "source_tier":  "county",
        "crawl_tier":   2,
        "county":       "Camden",
        "url":          "https://procurements.camdencounty.com/procurements/",
        "parser":       "camden_county",
        "access_type":  "Public access",
        "platform":     "County procurement portal",
        "notice_type":  "mixed",
        "crawl_freq":   "daily",
        "notes":        "Dedicated subdomain. Clean structured HTML. High value for South Jersey construction.",
    },
    {
        "id":           "county-monmouth",
        "name":         "Monmouth County Purchasing",
        "entity_type":  "County",
        "source_tier":  "county",
        "crawl_tier":   2,
        "county":       "Monmouth",
        "url":          "https://pol.co.monmouth.nj.us/",
        "parser":       "monmouth_county",
        "access_type":  "Limited public details",
        "platform":     "County procurement portal",
        "notice_type":  "mixed",
        "crawl_freq":   "daily",
        "notes":        "Searchable portal. Active construction program — Route 9, CR 516, bridge work.",
    },
    {
        "id":           "county-bergen",
        "name":         "Bergen County Bids",
        "entity_type":  "County",
        "source_tier":  "county",
        "crawl_tier":   2,
        "county":       "Bergen",
        "url":          "https://www.co.bergen.nj.us/purchasing",
        "legal_url":    "https://www.co.bergen.nj.us/current-legal-notices",
        "parser":       "generic_html_list",
        "access_type":  "Public access",
        "platform":     "County procurement portal",
        "notice_type":  "mixed",
        "crawl_freq":   "daily",
        "notes":        "Active construction — Route 4, Route 17 corridor work.",
    },
    {
        "id":           "county-hudson",
        "name":         "Hudson County Purchasing",
        "entity_type":  "County",
        "source_tier":  "county",
        "crawl_tier":   2,
        "county":       "Hudson",
        "url":          "https://www.hcnj.us/finance/purchasing",
        "parser":       "generic_html_list",
        "access_type":  "Public access",
        "platform":     "County procurement portal",
        "notice_type":  "mixed",
        "crawl_freq":   "daily",
    },
    {
        "id":           "county-gloucester",
        "name":         "Gloucester County Bids",
        "entity_type":  "County",
        "source_tier":  "county",
        "crawl_tier":   2,
        "county":       "Gloucester",
        "url":          "https://www.gloucestercountynj.gov/bids.aspx",
        "parser":       "gloucester_county",
        "access_type":  "Public access",
        "platform":     "County procurement portal",
        "notice_type":  "mixed",
        "crawl_freq":   "daily",
    },
    {
        "id":           "county-burlington",
        "name":         "Burlington County Bid Solicitations",
        "entity_type":  "County",
        "source_tier":  "county",
        "crawl_tier":   2,
        "county":       "Burlington",
        "url":          "https://www.co.burlington.nj.us/490/Bid-Solicitations",
        "parser":       "generic_html_list",
        "access_type":  "Public access",
        "platform":     "County procurement portal",
        "notice_type":  "mixed",
        "crawl_freq":   "daily",
    },
    {
        "id":           "county-middlesex",
        "name":         "Middlesex County Improvement Authority",
        "entity_type":  "County",
        "source_tier":  "county",
        "crawl_tier":   2,
        "county":       "Middlesex",
        "url":          "https://www.co.middlesex.nj.us/Government/Departments/PW/Pages/Bids.aspx",
        "parser":       "generic_html_list",
        "access_type":  "Public access",
        "platform":     "County procurement portal",
        "notice_type":  "mixed",
        "crawl_freq":   "daily",
    },
    {
        "id":           "county-union",
        "name":         "Union County Invitations to Bid",
        "entity_type":  "County",
        "source_tier":  "county",
        "crawl_tier":   2,
        "county":       "Union",
        "url":          "https://ucnj.org/departments/purchasing/",
        "parser":       "generic_html_list",
        "access_type":  "Public access",
        "platform":     "County procurement portal",
        "notice_type":  "mixed",
        "crawl_freq":   "daily",
    },
    {
        "id":           "county-morris",
        "name":         "Morris County Bids",
        "entity_type":  "County",
        "source_tier":  "county",
        "crawl_tier":   2,
        "county":       "Morris",
        "url":          "https://www.morriscountynj.gov/Departments/Purchasing",
        "parser":       "generic_html_list",
        "access_type":  "Public access",
        "platform":     "County procurement portal",
        "notice_type":  "mixed",
        "crawl_freq":   "daily",
    },
    {
        "id":           "county-ocean",
        "name":         "Ocean County Purchasing",
        "entity_type":  "County",
        "source_tier":  "county",
        "crawl_tier":   2,
        "county":       "Ocean",
        "url":          "https://www.co.ocean.nj.us/Purchasing",
        "parser":       "generic_html_list",
        "access_type":  "Public access",
        "platform":     "County procurement portal",
        "notice_type":  "mixed",
        "crawl_freq":   "daily",
    },
    {
        "id":           "county-mercer",
        "name":         "Mercer County Bidding Opportunities",
        "entity_type":  "County",
        "source_tier":  "county",
        "crawl_tier":   2,
        "county":       "Mercer",
        "url":          "https://www.mercercounty.org/government/purchasing/bids-rfps",
        "parser":       "generic_html_list",
        "access_type":  "Public access",
        "platform":     "County procurement portal",
        "notice_type":  "mixed",
        "crawl_freq":   "daily",
    },
    {
        "id":           "county-passaic",
        "name":         "Passaic County Purchasing",
        "entity_type":  "County",
        "source_tier":  "county",
        "crawl_tier":   2,
        "county":       "Passaic",
        "url":          "https://www.passaiccountynj.org/government/departments/purchasing",
        "parser":       "generic_html_list",
        "access_type":  "Public access",
        "platform":     "County procurement portal",
        "notice_type":  "mixed",
        "crawl_freq":   "weekly",
    },
    {
        "id":           "county-somerset",
        "name":         "Somerset County Purchasing",
        "entity_type":  "County",
        "source_tier":  "county",
        "crawl_tier":   2,
        "county":       "Somerset",
        "url":          "https://www.co.somerset.nj.us/government/departments/purchasing",
        "parser":       "generic_html_list",
        "access_type":  "Public access",
        "platform":     "County procurement portal",
        "notice_type":  "mixed",
        "crawl_freq":   "weekly",
    },
    {
        "id":           "county-atlantic",
        "name":         "Atlantic County Open Bids",
        "entity_type":  "County",
        "source_tier":  "county",
        "crawl_tier":   2,
        "county":       "Atlantic",
        "url":          "https://www.atlantic-county.org/purchasing/bids.asp",
        "parser":       "generic_html_list",
        "access_type":  "Public access",
        "platform":     "County procurement portal",
        "notice_type":  "mixed",
        "crawl_freq":   "weekly",
    },
    {
        "id":           "county-cape-may",
        "name":         "Cape May County Bids",
        "entity_type":  "County",
        "source_tier":  "county",
        "crawl_tier":   2,
        "county":       "Cape May",
        "url":          "https://capemaycountynj.gov/298/Purchasing",
        "parser":       "generic_html_list",
        "access_type":  "Public access",
        "platform":     "County procurement portal",
        "notice_type":  "mixed",
        "crawl_freq":   "weekly",
    },
    {
        "id":           "county-cumberland",
        "name":         "Cumberland County Bids",
        "entity_type":  "County",
        "source_tier":  "county",
        "crawl_tier":   2,
        "county":       "Cumberland",
        "url":          "https://www.cumberlandcountynj.gov/bids/",
        "parser":       "generic_html_list",
        "access_type":  "Public access",
        "platform":     "County procurement portal",
        "notice_type":  "mixed",
        "crawl_freq":   "weekly",
    },
    {
        "id":           "county-hunterdon",
        "name":         "Hunterdon County Bids",
        "entity_type":  "County",
        "source_tier":  "county",
        "crawl_tier":   2,
        "county":       "Hunterdon",
        "url":          "https://www.co.hunterdon.nj.us/purchasing.htm",
        "parser":       "generic_html_list",
        "access_type":  "Public access",
        "platform":     "County procurement portal",
        "notice_type":  "mixed",
        "crawl_freq":   "weekly",
    },
    {
        "id":           "county-warren",
        "name":         "Warren County Purchasing",
        "entity_type":  "County",
        "source_tier":  "county",
        "crawl_tier":   2,
        "county":       "Warren",
        "url":          "https://www.co.warren.nj.us/purchasing.html",
        "parser":       "generic_html_list",
        "access_type":  "Public access",
        "platform":     "County procurement portal",
        "notice_type":  "mixed",
        "crawl_freq":   "weekly",
    },
    {
        "id":           "county-sussex",
        "name":         "Sussex County Purchasing",
        "entity_type":  "County",
        "source_tier":  "county",
        "crawl_tier":   2,
        "county":       "Sussex",
        "url":          "https://www.sussex.nj.us/government/departments/purchasing",
        "parser":       "generic_html_list",
        "access_type":  "Public access",
        "platform":     "County procurement portal",
        "notice_type":  "mixed",
        "crawl_freq":   "weekly",
    },
    {
        "id":           "county-salem",
        "name":         "Salem County Purchasing",
        "entity_type":  "County",
        "source_tier":  "county",
        "crawl_tier":   2,
        "county":       "Salem",
        "url":          "https://www.salemcountynj.gov/purchasing",
        "parser":       "generic_html_list",
        "access_type":  "Public access",
        "platform":     "County procurement portal",
        "notice_type":  "mixed",
        "crawl_freq":   "weekly",
    },

    # ─────────────────────────────────────────────────────────────────────────
    # TIER 3 — HIGH-VALUE MUNICIPAL PORTALS (seeded manually, rest from SoS)
    # ─────────────────────────────────────────────────────────────────────────

    {
        "id":           "municipal-newark",
        "name":         "City of Newark Bid Postings",
        "entity_type":  "Municipality",
        "source_tier":  "municipal",
        "crawl_tier":   3,
        "county":       "Essex",
        "url":          "https://www.newarknj.gov/card/office-of-central-purchasing",
        "parser":       "generic_html_list",
        "access_type":  "Public access",
        "platform":     "Agency website",
        "notice_type":  "mixed",
        "crawl_freq":   "daily",
    },
    {
        "id":           "municipal-jersey-city",
        "name":         "City of Jersey City Bid Openings",
        "entity_type":  "Municipality",
        "source_tier":  "municipal",
        "crawl_tier":   3,
        "county":       "Hudson",
        "url":          "https://www.jerseycitynj.gov/government/purchasing",
        "parser":       "generic_html_list",
        "access_type":  "Public access",
        "platform":     "Agency website",
        "notice_type":  "mixed",
        "crawl_freq":   "daily",
    },
    {
        "id":           "municipal-paterson",
        "name":         "City of Paterson Purchasing",
        "entity_type":  "Municipality",
        "source_tier":  "municipal",
        "crawl_tier":   3,
        "county":       "Passaic",
        "url":          "https://www.patersonnj.gov/egov/apps/document/center.egov?view=category&id=54",
        "parser":       "generic_html_list",
        "access_type":  "Public access",
        "platform":     "Agency website",
        "notice_type":  "mixed",
        "crawl_freq":   "daily",
    },
    {
        "id":           "municipal-elizabeth",
        "name":         "City of Elizabeth Bid Postings",
        "entity_type":  "Municipality",
        "source_tier":  "municipal",
        "crawl_tier":   3,
        "county":       "Union",
        "url":          "https://www.elizabethnj.org/purchasing",
        "parser":       "generic_html_list",
        "access_type":  "Public access",
        "platform":     "Agency website",
        "notice_type":  "mixed",
        "crawl_freq":   "weekly",
    },
    {
        "id":           "municipal-trenton",
        "name":         "City of Trenton Legal Ads",
        "entity_type":  "Municipality",
        "source_tier":  "municipal",
        "crawl_tier":   3,
        "county":       "Mercer",
        "url":          "https://www.trentonnj.org/current-legal-notices",
        "parser":       "generic_html_list",
        "access_type":  "Public access",
        "platform":     "Agency website",
        "notice_type":  "public_notice",
        "crawl_freq":   "weekly",
    },
    {
        "id":           "municipal-camden-city",
        "name":         "City of Camden Purchasing",
        "entity_type":  "Municipality",
        "source_tier":  "municipal",
        "crawl_tier":   3,
        "county":       "Camden",
        "url":          "https://www.ci.camden.nj.us/bids/",
        "parser":       "generic_html_list",
        "access_type":  "Public access",
        "platform":     "Agency website",
        "notice_type":  "mixed",
        "crawl_freq":   "weekly",
    },

    # ─────────────────────────────────────────────────────────────────────────
    # TIER 4 — PAYWALLED PLATFORMS (notice text only)
    # ─────────────────────────────────────────────────────────────────────────

    {
        "id":           "platform-bidnet",
        "name":         "BidNet (NJ agencies)",
        "entity_type":  "Platform",
        "source_tier":  "paywalled",
        "crawl_tier":   4,
        "county":       "Various",
        "url":          "https://www.bidnet.com/bneattachments?bneattachments",
        "parser":       "bidnet",
        "access_type":  "Platform subscription required",
        "platform":     "BidNet",
        "notice_type":  "mixed",
        "crawl_freq":   "weekly",
        "notes":        "Public notice list accessible. Documents require subscription. Stamp all records as paywall=True.",
    },
    {
        "id":           "platform-questcdn",
        "name":         "QuestCDN (NJ agencies)",
        "entity_type":  "Platform",
        "source_tier":  "paywalled",
        "crawl_tier":   4,
        "county":       "Various",
        "url":          "https://www.questcdn.com/",
        "parser":       "questcdn",
        "access_type":  "Platform submission required",
        "platform":     "QuestCDN",
        "notice_type":  "mixed",
        "crawl_freq":   "weekly",
        "notes":        "Notice list may be browsable. Flag all as paywalled.",
    },
]

# Quick lookups
SOURCES_BY_ID   = {s["id"]: s for s in NOTICE_SOURCES}
TIER1_SOURCES   = [s for s in NOTICE_SOURCES if s["crawl_tier"] == 1]
TIER2_SOURCES   = [s for s in NOTICE_SOURCES if s["crawl_tier"] == 2]
TIER3_SOURCES   = [s for s in NOTICE_SOURCES if s["crawl_tier"] == 3]
TIER4_SOURCES   = [s for s in NOTICE_SOURCES if s["crawl_tier"] == 4]
DAILY_SOURCES   = [s for s in NOTICE_SOURCES if s.get("crawl_freq") == "daily"]
WEEKLY_SOURCES  = [s for s in NOTICE_SOURCES if s.get("crawl_freq") == "weekly"]
